# Discovery Server Access

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:log4jdbc:mariadb://localhost:3306/myshop2024?autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true
    username: root
    password: qjawnalwn22@

#jasypt:
#  encryptor:
#    bean: jasyptStringEncryptor
#    password: 5ReC2cBs


logger:
  stacktrace: true

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

server:
  port: 7773
  servlet:
    context-path: /api/

file:
  path: /uploads/

img:
  path: /uploads/
  url: http://www.navidi7311.shop/uploads
#  url: http://www.ipmt.com/uploads





