# Discovery Server Access

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://4.217.186.166:3306/aivlebig?autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true
    username: root
    password: aivle202406

  mail:
    username: ${AZURE_KEY_VAULT_MAIL_USERNAME}
    password: ${AZURE_KEY_VAULT_MAIL_PASSWORD}

jwt:
  secret: ${AZURE_KEY_VAULT_JWT_SECRET}

cors:
  allowed-origins:
    - http://4.217.186.166:3000

#jasypt:
#  encryptor:
#    bean: jasyptStringEncryptor
#    password: 5ReC2cBs


logger:
  stacktrace: true

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

server:
  port: 7773
  servlet:
    context-path: /api/

file:
  path: /uploads/

img:
  path: /uploads/
  url: http://www.navidi7311.shop/uploads
#  url: http://www.ipmt.com/uploads





