spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://4.217.186.166:3306/aivlebig?autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true
    username: root
    password: aivle202406

file:
  path: /Users/bj_develop/Desktop/

img:
  path: /Users/bj_develop/Desktop/
  url: /Users/bj_develop/Downloads


secret:
  access: acc
  refresh: ref